name: Notify issues

on:
  issues:
    types: [opened]

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@v0.0.2
      env:
        API_KEY: ${{ secrets.PUSH_API_KEY }}
        MESSAGE: "An issue has been opened."
