# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a single command using the runners shell
      - name: sanity pull-request
        if: github.event_name != 'pull_request'
        run: |
          echo "Github actions is sane, running for branch : ${GITHUB_REF#refs/heads/}"
      # Runs a set of commands using the runners shell
      - name: compile and test pull-request
        if: github.event_name != 'pull_request'
        run: |
          echo "pulling docker image for branch"
          docker pull dealii/dealii:master-focal
          echo "Docker image is good, ready for action!"
          docker run --workdir=/home/dealii/workspace --volume ${{ github.workspace }}:/home/dealii/workspace /bin/sh -c "git checkout ${GITHUB_REF#refs/heads/} && cmake -B $(pwd)/build -DCMAKE_BUILD_TYPE=Release && cd build/ && make -j2 ";
      - name: sanity master
        if: github.event_name == 'pull_request'
        run: |
          echo "Github actions is sane, running for master"
      - name: compile and test master
        if: github.event_name == 'pull_request'
        run: |
          echo "pulling docker image for master"
          docker pull dealii/dealii:master-focal
          echo "Docker image is good, ready for action!"
          docker run --workdir=/home/dealii/workspace --volume ${{ github.workspace }}:/home/dealii/workspace /bin/sh -c "git checkout ${GITHUB_REF#refs/heads/} && cmake -B $(pwd)/build -DCMAKE_BUILD_TYPE=Release && cd build/ && make -j2 ";
  build-debug:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: sanity pull-request
        if: github.event_name != 'pull_request'
        run: |
          echo "Github actions is sane, running for branch : ${GITHUB_REF#refs/heads/}"
      # Runs a set of commands using the runners shell
      - name: compile and test pull-request
        if: github.event_name != 'pull_request'
        run: |
          echo "pulling docker image for branch"
          docker pull dealii/dealii:master-focal
          echo "Docker image is good, ready for action!"
          echo "${{ secrets.GITHUB_TOKEN }}"
          docker run --workdir=/home/dealii/workspace --volume ${{ github.workspace }}:/home/dealii/workspace /bin/sh -c "git checkout ${GITHUB_REF#refs/heads/} && cmake -B $(pwd)/build -DCMAKE_BUILD_TYPE=Debug && cd build/ && make -j2 ";
          
      - name: sanity master
        if: github.event_name == 'pull_request'
        run: |
          echo "Github actions is sane, running for master"
      - name: compile and test master
        if: github.event_name == 'pull_request'
        run: |
          echo "pulling docker image for master"
          docker pull dealii/dealii:master-focal
          echo "Docker image is good, ready for action!"
          docker run --workdir=/home/dealii/workspace --volume ${{ github.workspace }}:/home/dealii/workspace /bin/sh -c "git checkout ${GITHUB_REF#refs/heads/} && cmake -B $(pwd)/build -DCMAKE_BUILD_TYPE=Debug && cd build/ && make -j2 ";
